########## Test for user administration ###########

### Test Create User
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "name": "Doe, John",
  "birthday": "01.01.2000",
  "email": "john.doe@example.com"
}
###

### Test Update User
PUT http://localhost:8080/api/user/1
Content-Type: application/json

{
  "name": "John Updated",
  "email": "john.updated@example.com"
}
###

### Test Delete User
DELETE http://localhost:8080/api/user/1
###

### Test Find User By ID
GET http://localhost:8080/api/user/1
Accept: application/json
###

### Test Find All User
GET http://localhost:8080/api/user
Accept: application/json


########## Test event administration ###########

### Test Create Event
POST http://localhost:8080/api/event
Content-Type: application/json

{
  "title": "RB Spiel",
  "place": "Leipzig",
  "date": "01.06.2025",
  "quota": 4
}
###

### Test Update Event
PUT http://localhost:8080/api/event/3
Content-Type: application/json

{
  "title": "Bayern Spiel",
  "place": "Leipzig",
  "date": "30.02.2026",
  "quota": 3
}
###

### Test Delete Event
DELETE http://localhost:8080/api/event/1
###

### Test Delete All Events
DELETE http://localhost:8080/api/event
###

### Test Find Event By ID
GET http://localhost:8080/api/event/1
Accept: application/json
###

### Test Find All Events
GET http://localhost:8080/api/event
Accept: application/json
###

### Test Has Tickets Left
GET http://localhost:8080/api/event/1/tickets_left
Accept: application/json
###


########## Test ticket administration ###########

### Test puchase Ticket
POST http://localhost:8080/api/ticket/1/1
Content-Type: application/json
###

### Test cancel Ticket
DELETE http://localhost:8080/api/ticket/1
###

### Test Find Tickets By UserId
GET http://localhost:8080/api/ticket/user/1
Accept: application/json
###

### Test Find Tickets By EventId
GET http://localhost:8080/api/ticket/event/1
Accept: application/json
###
