### Test Create User
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "name": "Doe, John",
  "birthday": "01.01.2000",
  "email": "john.doe123@example.com"
}

###

### Test Update User
PUT http://localhost:8080/api/user/1
Content-Type: application/json

{
  "name": "John Updated",
  "email": "john.updated@example.com"
}

###

### Test Delete User
DELETE http://localhost:8080/api/user/1

###

### Test Find User By ID
GET http://localhost:8080/api/user/1
Accept: application/json

###

### Test Find All User
GET http://localhost:8080/api/user
Accept: application/json


##########################################

### Test Create Event
POST http://localhost:8080/api/event
Content-Type: application/json

{
  "title": "RB Spiel",
  "place": "Leipzig",
  "date": "30.02.2026",
  "quota": 200
}
###

### Test Update Event
PUT http://localhost:8080/api/event/1
Content-Type: application/json

{
  "title": "Bayern Spiel",
  "place": "Leipzig",
  "date": "30.02.2026",
  "quota": 101
}
###

### Test Delete Event
DELETE http://localhost:8080/api/event/1
###

### Test Delete Event
DELETE http://localhost:8080/api/event
###

### Test Find Event By ID
GET http://localhost:8080/api/event/1
Accept: application/json
###

### Test Find All Events
GET http://localhost:8080/api/event
Accept: application/json

